### PR TITLE
warn and skip layers with missing WOF metafiles

### LINKED ISSUE #157: Log an error message if a layer's meta file cannot be found
Currently, if there is no data at all, including meta file, for a particular layer (for example some of the ones we have recently added such as `empire`), the pip service will load other layers, and then hang indefinitely while waiting for the layers with missing data to load. No message of any kind indicating that the layer data was missing is printed, so its quite hard to tell what went wrong.

Replaces https://github.com/pelias/wof-pip-service/issues/89

### PR DESCRIPTION
**Pull request by trescube**
Fixes #157 

Introduces boolean `imports.admin.missingMetafilesAreFatal` for what to do when WOF metafiles are missing while starting.  Defaults to *false* so we'll have to enable in our configs.  /src/pip/index.js returns an error in the callback while src/localPipResolver.js throws an error which will shutdown importers.

### CODE REVIEW

File: src/pip/index.js [hunk 1]
```diff
@@ -43,6 +43,17 @@ module.exports.create = function createPIPService(datapath, layers, localizedAdm
   // ie - _.intersection([1, 2, 3], [3, 1]) === [1, 3]
   layers = _.intersection(defaultLayers, _.isEmpty(layers) ? defaultLayers : layers);
 
+  // further refine the layers by filtering out layers for which there is not metafile
+  layers = layers.filter(layer => {
+    const filename = path.join(datapath, 'meta', `wof-${layer}-latest.csv`);
+
+    if (!fs.existsSync(filename)) {
+      logger.warn(`unable to locate ${filename}`);
```
Comment (orangejulius) [inline src/pip/index.js]: If we make this a warning, all our builds will silently proceed with missing admin lookup data. At least now the build would hang since the admin lookup data will never finish loading. Kinda like the case of being unable to load individual files with the whosonfirst importer, we might want to either make this a fatal error or at least have the option to make it one.

Comment (trescube) [reply src/pip/index.js]: Switched to an error message.

File: src/pip/index.js [hunk 2]
```diff
@@ -43,6 +43,17 @@ module.exports.create = function createPIPService(datapath, layers, localizedAdm
   // ie - _.intersection([1, 2, 3], [3, 1]) === [1, 3]
   layers = _.intersection(defaultLayers, _.isEmpty(layers) ? defaultLayers : layers);
 
+  // further refine the layers by filtering out layers for which there is not metafile
+  layers = layers.filter(layer => {
+    const filename = path.join(datapath, 'meta', `wof-${layer}-latest.csv`);
+
+    if (!fs.existsSync(filename)) {
+      logger.error(`unable to locate ${filename}`);
```
Comment (orangejulius) [inline src/pip/index.js]: To follow up on the conversation we had in person, I really believe this should have a configuration option to throw a fatal error (one that shuts down the entire admin lookup process). Otherwise a situation will inevitably arise where we run builds without all the admin data we wanted and don't find out until it's done, which wastes a lot of time.

File: src/localPipResolver.js [hunk 3]
```diff
@@ -14,7 +14,10 @@ function LocalPipService(datapath, layers) {
   const self = this;
 
   createPipService(datapath, _.defaultTo(layers, []), false, (err, service) => {
-     self.pipService = service;
+    if (err) {
```
Comment (orangejulius) [inline src/localPipResolver.js]: wait we were swallowing all errors here? hah. well, good thing we fixed it.

File: src/pip/index.js [hunk 4]
```diff
@@ -43,6 +44,26 @@ module.exports.create = function createPIPService(datapath, layers, localizedAdm
...
+      missingMetafiles.push(`wof-${layer}-latest.csv`);
+      return false;
+    }
+    return true;
+  });
+
+  // if there are missing metafiles and this is fatal, then return an error
+  if (!_.isEmpty(missingMetafiles) && missingMetafilesAreFatal) {
+    return callback(`unable to locate meta files in ${path.join(datapath, 'meta')}: ${missingMetafiles.join(', ')}`);
```
Comment (orangejulius) [inline src/pip/index.js]: i like that it logs the missing files. very nice touch

File: schema.js [hunk 5]
```diff
@@ -6,7 +6,8 @@ module.exports = Joi.object().keys({
     adminLookup: Joi.object().keys({
       // default maxConcurrentReqs to # of cpus/cores * 10
       maxConcurrentReqs: Joi.number().integer().default(cpus().length*10),
-      enabled: Joi.boolean().default(true)
+      enabled: Joi.boolean().default(true),
+      missingMetafilesAreFatal: Joi.boolean().default(false)
     }).unknown(true),
```
Comment (orangejulius) [inline schema.js]: line 10 here (`unknown(true)`) means it's ok for me to add this new option to all our config files in Mapzen Search right now, yes? If i don't do it now I'm sure we'll forget :P

Comment (trescube) [reply schema.js]: Yes, you can add whatever you want to `imports.adminLookup`.

Comment (orangejulius) [reply schema.js]: Great. it's done. hopefully we don't decide to last minute bikeshed the name
